markdown: pandoc
pandoc:
    skip: false
    flags: '--csl=apa.csl --bibliography=ref.bib --smart -V lang=spanish
            --section-divs --email-obfuscation=references'
    outputs:
        - pdf: '-V fontsize=10pt,a5paper,twoside
                -V documentclass=book
                -V geometry=hcentering
                -V geometry=bindingoffset=1cm
                --latex-engine=xelatex
                --table-of-contents
                --include-in-header=_layouts/header.tex
                --include-before-body=_layouts/license.tex'
        - epub: '--epub-stylesheet=css/bootstrap.css'
        - mediawiki
        - rst
        - latex: '-V fontsize=10pt,a5paper,twoside
                  -V documentclass=book
                  -V geometry=hcentering
                  -V geometry=bindingoffset=1cm
                  --latex-engine=xelatex
                  --table-of-contents
                  --include-in-header=_layouts/header.tex
                  --include-before-body=_layouts/license.tex'

destination: /srv/http/endefensadelsl.org

permalink: ":title.html"

lsi: false

torrent:
  file: endefensadel.torrent
